name: biolumi_calcium_cli
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-image
  - opencv
  - tifffile
  - imageio
  - pillow
  - jupyter
  - ipython
  - napari
  - pyqt  # required GUI backend for napari
  - pip